"""Bind a proposed semantic request into an authorized, version-pinned plan.

The model proposes IDs and operators. The binder resolves them to exact versions, runs rule
closure to a fixed point, plans joins, reauthorizes every reference it added, and records a
coverage entry for every requested concept.

Nothing here trusts the proposal beyond "these are the IDs the user seems to mean".
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from app.catalog.service import CatalogService
from app.contracts.coverage import ConceptCoverage, CoverageMatrix, CoverageState
from app.contracts.errors import GovernedError, ReasonCode
from app.contracts.expressions import (
    BoolOp,
    ColumnExpr,
    Comparison,
    LiteralExpr,
    Membership,
    Predicate,
)
from app.contracts.ids import table_id_of
from app.contracts.scope import Action, TrustedScope
from app.contracts.semantic_plan import (
    BoundDimension,
    BoundMetric,
    BoundSemanticPlan,
    BoundTimeSpec,
    ExpectedResultContract,
    ProposedFilter,
    SemanticRequest,
)
from app.relationships.planner import JoinPlan, JoinPlanner
from app.semantics.metrics import MetricService
from app.semantics.rules import ClosureInput, ClosureResult, RuleEngine


def _alias(object_id: str) -> str:
    """Deterministic output alias generated by code, never by a model."""
    leaf = object_id.rpartition(".")[2]
    return re.sub(r"[^a-z0-9_]", "_", leaf.lower())


def expected_output_columns(
    request: SemanticRequest, catalog: CatalogService
) -> tuple[str, ...]:
    """Output aliases this request will project, derived the same way the binder derives
    them. Shared so a repair cannot disagree with binding about what exists."""
    columns: list[str] = []
    if request.time_range and request.time_grain:
        columns.append(request.time_grain.value)
    for dim_id in request.dimension_ids:
        try:
            columns.append(_alias(catalog.snapshot.get("dimensions", dim_id).id))
        except GovernedError:
            continue
    for metric_id in request.metric_ids:
        try:
            record = catalog.snapshot.get("metrics", metric_id)
        except GovernedError:
            continue
        unit = "_" + record.unit.lower() if record.unit else ""
        columns.append(_alias(record.id) + unit)
    return tuple(columns)


@dataclass(frozen=True)
class BindResult:
    plan: BoundSemanticPlan
    join_plan: JoinPlan
    closure: ClosureResult


class Binder:
    def __init__(
        self,
        catalog: CatalogService,
        metrics: MetricService,
        rules: RuleEngine,
        joins: JoinPlanner,
    ) -> None:
        self.catalog = catalog
        self.metrics = metrics
        self.rules = rules
        self.joins = joins

    def bind(
        self,
        request: SemanticRequest,
        scope: TrustedScope,
        *,
        plan_id: str,
        plan_revision: int = 1,
    ) -> BindResult:
        coverage = CoverageMatrix()

        if not request.metric_ids:
            raise GovernedError(
                ReasonCode.UNSUPPORTED_CAPABILITY,
                "This slice supports metric-based questions only; ad hoc measures are not yet "
                "a certified operator.",
            )
        if len(request.metric_ids) > 1:
            raise GovernedError(
                ReasonCode.UNSUPPORTED_CAPABILITY,
                "Multi-metric requests need conformed-grain aggregation, which is not yet a "
                "certified operator.",
            )

        # -- metrics ------------------------------------------------------
        metric_id = request.metric_ids[0]
        metric_record = self.catalog.snapshot.get("metrics", metric_id)
        metric_ref = str(metric_record.ref)
        closure = self.metrics.resolve(metric_ref, scope)
        metric = closure.metric
        coverage = coverage.with_entry(
            ConceptCoverage(
                concept=metric_id,
                kind="metric",
                state=CoverageState.RESOLVED,
                resolved_ref=metric_ref,
                evidence_ref=f"catalog:{metric_ref}",
            )
        )

        bound_metric = BoundMetric(
            ref=metric_ref,
            expression=metric.expression,
            population=metric.population,
            base_table=metric.base_table,
            base_grain=metric.base_grain,
            unit=metric.unit,
            output_alias=_alias(metric.id) + ("_" + metric.unit.lower() if metric.unit else ""),
        )

        # -- dimensions ---------------------------------------------------
        bound_dims: list[BoundDimension] = []
        required_rel_refs: set[str] = set()
        for dim_id in request.dimension_ids:
            dim_record = self.catalog.snapshot.get("dimensions", dim_id)
            dim_ref = str(dim_record.ref)
            self.metrics.check_dimension_allowed(metric, dim_id)
            column, rel_ref = self.metrics.resolve_dimension_columns(dim_ref, scope)
            if rel_ref:
                required_rel_refs.add(rel_ref)
            bound_dims.append(
                BoundDimension(
                    ref=dim_ref,
                    column=column,
                    output_alias=_alias(dim_record.id),
                    entity_role=dim_record.entity_role,
                    temporal_binding=dim_record.temporal_binding,
                    via_relationship_ref=rel_ref,
                )
            )
            coverage = coverage.with_entry(
                ConceptCoverage(
                    concept=dim_id,
                    kind="dimension",
                    state=CoverageState.RESOLVED,
                    resolved_ref=dim_ref,
                    evidence_ref=f"catalog:{dim_ref}",
                )
            )

        # -- time ---------------------------------------------------------
        bound_time: BoundTimeSpec | None = None
        if request.time_range:
            grain = request.time_grain
            if grain and grain not in metric.time.grains:
                raise GovernedError(
                    ReasonCode.UNSUPPORTED_CAPABILITY,
                    f"Metric {metric_ref} does not support the {grain} grain; supported: "
                    f"{', '.join(g.value for g in metric.time.grains)}",
                    subject=str(grain),
                )
            bound_time = BoundTimeSpec(
                column=metric.time.time_column,
                range=request.time_range,
                grain=grain,
                output_alias=grain.value if grain else None,
                calendar_ref=metric.time.calendar_ref,
            )
            coverage = coverage.with_entry(
                ConceptCoverage(
                    concept="time range",
                    kind="time",
                    state=CoverageState.RESOLVED,
                    resolved_ref=f"{request.time_range.start.isoformat()}/"
                    f"{request.time_range.end_exclusive.isoformat()}",
                    evidence_ref=f"catalog:{metric_ref}#time",
                    note="Half-open interval; end is exclusive.",
                )
            )

        # -- user filters -------------------------------------------------
        user_filters = tuple(
            self._bind_filter(f, scope, metric) for f in request.filters
        )
        for f in request.filters:
            coverage = coverage.with_entry(
                ConceptCoverage(
                    concept=f"{f.target_id} {f.op}",
                    kind="filter",
                    state=CoverageState.RESOLVED,
                    resolved_ref=f.target_id,
                    evidence_ref=f"catalog:{f.target_id}",
                )
            )

        # -- rule closure -------------------------------------------------
        seed_columns = set(closure.all_columns) | {d.column for d in bound_dims}
        for pred in user_filters:
            from app.contracts.expressions import columns_in

            seed_columns |= columns_in(pred)
        seed_tables = {table_id_of(c) for c in seed_columns} | set(closure.tables)

        rule_closure = self.rules.close(
            ClosureInput(
                tables=frozenset(seed_tables),
                columns=frozenset(seed_columns),
                metric_refs=frozenset({metric_ref}),
                entities=frozenset({metric.base_entity}),
                relationship_refs=frozenset(required_rel_refs),
                slots={},
            ),
            scope,
        )

        if rule_closure.semantic_requirements:
            raise GovernedError(
                ReasonCode.MANDATORY_RULE_UNRESOLVED,
                "Semantic requirement(s) unresolved for this plan: "
                + ", ".join(rule_closure.semantic_requirements),
            )

        for ref in metric.required_rule_refs:
            if ref not in rule_closure.applied_rule_refs:
                raise GovernedError(
                    ReasonCode.MANDATORY_RULE_UNRESOLVED,
                    f"Metric {metric_ref} requires rule {ref}, which did not activate. A "
                    f"mandatory dependency is never optional.",
                    subject=ref,
                )
            coverage = coverage.with_entry(
                ConceptCoverage(
                    concept=ref,
                    kind="rule",
                    state=CoverageState.RESOLVED,
                    resolved_ref=ref,
                    evidence_ref=f"rule:{ref}",
                    note="Mandatory population rule; applied whether or not requested.",
                )
            )

        # -- joins --------------------------------------------------------
        required_rel_refs |= set(rule_closure.relationship_refs)
        join_plan = self.joins.plan(
            metric.base_table,
            rule_closure.tables,
            scope,
            required_relationship_refs=frozenset(required_rel_refs),
            forbid_multiplying=True,
        )

        if not join_plan.is_additive_safe:
            raise GovernedError(
                ReasonCode.FAN_OUT_UNPROVEN,
                f"Join plan multiplies {metric.base_table} rows; an additive measure cannot be "
                f"aggregated over it.",
            )

        # -- final authorization sweep over every reference ----------------
        all_columns = set(seed_columns)
        for obligation in rule_closure.obligations:
            if obligation.predicate is not None:
                from app.contracts.expressions import columns_in

                all_columns |= columns_in(obligation.predicate)
        for join in join_plan.joins:
            for pred in join.relationship.predicates:
                all_columns |= {pred.left_column, pred.right_column}

        self.catalog.require_columns_usable(
            frozenset(all_columns) - closure.measure_columns, scope, Action.USE_IN_PREDICATE
        )
        self.catalog.require_columns_usable(closure.measure_columns, scope, Action.READ)

        # -- result contract ----------------------------------------------
        columns: list[str] = []
        grain: list[str] = []
        if bound_time and bound_time.output_alias:
            columns.append(bound_time.output_alias)
            grain.append(bound_time.output_alias)
        for d in bound_dims:
            columns.append(d.output_alias)
            grain.append(d.output_alias)
        columns.append(bound_metric.output_alias)

        result_contract = ExpectedResultContract(
            columns=tuple(columns),
            grain=tuple(grain),
            unit=metric.unit,
            unique_keys=tuple(grain),
            missing_groups=metric.missing_groups,
            empty_set_policy=metric.empty_set_policy,
        )

        order_by = request.order_by or tuple(
            {"field": g, "direction": "asc"} for g in grain
        )
        unknown = [
            key.field for key in request.order_by if key.field not in columns
        ]
        if unknown:
            raise GovernedError(
                ReasonCode.VALIDATION_FAILED,
                f"Sort key(s) {', '.join(unknown)} name no projected column; available "
                f"columns are {', '.join(columns)}",
                subject=unknown[0],
            )

        plan = BoundSemanticPlan(
            plan_id=plan_id,
            plan_revision=plan_revision,
            operation=request.operation,
            snapshot_id=scope.snapshot_id,
            policy_epoch=scope.policy_epoch,
            metrics=(bound_metric,),
            dimensions=tuple(bound_dims),
            time=bound_time,
            filters=user_filters,
            obligations=rule_closure.obligations,
            relationship_refs=join_plan.relationship_refs,
            rule_refs=rule_closure.applied_rule_refs,
            metric_refs=(metric_ref,),
            order_by=tuple(order_by),
            limit=request.limit,
            result_contract=result_contract,
            coverage=coverage,
            evidence_refs=(f"snapshot:{scope.snapshot_id}", f"metric:{metric_ref}"),
        )
        return BindResult(plan=plan, join_plan=join_plan, closure=rule_closure)

    def _bind_filter(
        self, proposed: ProposedFilter, scope: TrustedScope, metric
    ) -> Predicate:
        """Resolve a proposed filter into a typed predicate over a real, authorized column."""
        target = proposed.target_id
        # A filter may name a dimension; resolve it to its underlying column.
        try:
            dim = self.catalog.snapshot.get("dimensions", target)
            column_id = dim.column
        except GovernedError:
            column_id = target

        column = self.catalog.get_column(column_id, scope)
        self.catalog.require_columns_usable(
            frozenset({column_id}), scope, Action.USE_IN_PREDICATE
        )

        literal_type = _literal_type_for(column.data_type)
        operands = tuple(
            LiteralExpr(type=literal_type, value=v) for v in proposed.values
        )

        if proposed.op in ("in", "not_in"):
            return Membership(
                negated=proposed.op == "not_in",
                left=ColumnExpr(column_ref=column_id),
                members=operands,
            )
        if len(operands) != 1:
            raise GovernedError(
                ReasonCode.UNSUPPORTED_OPERATOR,
                f"Operator {proposed.op!r} takes exactly one value",
                subject=target,
            )
        return Comparison(
            op=proposed.op, left=ColumnExpr(column_ref=column_id), right=operands[0]
        )


def _literal_type_for(data_type: str) -> str:
    upper = data_type.upper()
    if upper.startswith("BOOL"):
        return "boolean"
    if upper.startswith(("INT", "BIGINT", "SMALLINT")):
        return "integer"
    if upper.startswith(("DECIMAL", "NUMERIC", "DOUBLE", "FLOAT")):
        return "decimal"
    if "TIMESTAMP" in upper:
        return "instant"
    if upper.startswith("DATE"):
        return "date"
    return "string"


__all__ = ["BindResult", "Binder", "BoolOp"]
